title: "Saba Karimi"
description: "Ph.D. student at Georgia Tech in Materials Science & Engineering"
url: "https://sabbkarr.github.io"   
theme: "minimal"
baseurl: ""
plugins:
  - jekyll-feed

nav:
  - title: "About"
    url: /about/
  - title: "Research"
    url: /research/
  - title: "CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Contact"
    url: /contact/
  - title: "Blog"
    url: /blog/
